### ISSUE TITLE
state update when onClick

### ISSUE THREAD

**Issue by aelbore** [WebReflection/uhooks#4]
do you have idea why state value didnt update? 
but UI updates

```typescript
import { hooked, useState } from 'uhooks';
import { render, html } from 'lit-html';

const useReactive = (objects) => {
  const values = {};
  const keys = Object.keys(objects);
  for (const key of keys) {
    const [value, set] = useState(objects[key]);
    Object.defineProperty(values, key, {
      enumerable: true,
      get: () => value,
      set,
    });
  }
  return values;
};

const callback = (initial) => {
  const state = useReactive(initial);

  const onClick = () => {
    state.name = '1212';
    /// this doesnt update the new value
    /// but the UI updates
    console.log(state.name);
  };

  render(
    html`<button @click=${onClick}>Click Me ${state.name}</button>`,
    document.getElementById('app')
  );
};

const element = hooked(callback);

element({ name: 'Joe' });
```

**Comment by WebReflection** [comment]
this can work only if the amount of keys is always the same .. it's like conditional or ternary hook which is not allowed *AFAIK* even in React. It's not likely going to happen or work anywhere unless I rewrite the whole logic which I am afraid I have no time, or interest, in doing, also because like I've said not even React would work here, but if it does, I might have a look in the future, but these days I really have little extra time, sorry.

**Comment by WebReflection** [comment]
P.S. [this library achieves the same goal](https://github.com/WebReflection/reactive-props#readme), give it a try as it might centralize the single `useState` call hence work for your case too.

**Comment by aelbore** [comment]
@WebReflection thanks, i realise i can use `useEffect` by the way `uhooks` is really good
